import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "./user/_utils/auth-context";
import { CartProvider} from "./user/_utils/cart-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "e-commerce-store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <CartProvider>
          {children}
          </CartProvider>
          </AuthContextProvider>
      </body>
    </html>
  );
}
